name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # run when pushing to main branch
  workflow_dispatch: # allow manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: sdali9019
        password: dawoods45

    - name: Build and Push Docker image
      uses: sdali9019
      with:
        context: .
        push: true
        tags: sdali9019/github-action:1.0
